azure-pipelines.release.yml, azure-pipelines.yml
VIH-6716
fix release pipeline
```
[ ] Yes
[x] No
```
=> VIH-6716 fix release pipeline

azure-pipelines.release.yml, azure-pipelines.yml
VIH-6717 
Update settings from KV
```
[ ] Yes
[x] No
```
=> VIH-6717 Update settings from KV

azure-pipelines.yml
VIH-6716
enable sonar
```
[ ] Yes
[x] No
```
=> VIH-6716 enable sonar

NotificationApi/NotificationApi.Contract/Requests/AddNotificationRequest.cs, NotificationApi/NotificationApi.UnitTests/Controller/CreateNotificationControllerTests.cs, NotificationApi/NotificationApi/Controllers/CreateNotificationController.cs
VIH-6804
Added contract for AddNotificationRequest
```
[ ] Yes
[x] No
```
=> VIH-6804 Added contract for AddNotificationRequest

NotificationApi/NotificationApi.AcceptanceTests/packages.lock.json, NotificationApi/NotificationApi.Client/NotificationApi.Client.csproj, NotificationApi/NotificationApi.Contract/NotificationApi.Contract.csproj, NotificationApi/NotificationApi.Contract/packages.lock.json, NotificationApi/NotificationApi.IntegrationTests/packages.lock.json, NotificationApi/NotificationApi.Services/packages.lock.json, NotificationApi/NotificationApi.UnitTests/packages.lock.json, NotificationApi/NotificationApi/packages.lock.json
VIH-6716 
Add project dependencies for client project
```
[ ] Yes
[x] No
```
=> VIH-6716 Add project dependencies for client project

NotificationApi/NotificationApi.Client/NotificationApiClient.cs, NotificationApi/NotificationApi/nswag.json
https://tools.hmcts.net/jira/browse/VIH-6762
Added missing interface to notification client
```
[ ] Yes
[ ] No
```
=> VIH-6762 Added missing interface to notification client

NotificationApi/NotificationApi.AcceptanceTests/Hooks/ConfigHooks.cs, NotificationApi/NotificationApi.Client/NotificationApiClient.cs, NotificationApi/NotificationApi.Client/NotificationApiClientFactory.cs, NotificationApi/NotificationApi.Services/packages.lock.json, NotificationApi/NotificationApi/nswag.json
VIH-6764
remove base url from ctor for client
```
[ ] Yes
[x] No
```
=> VIH-6764 remove base url from ctor for client

NotificationApi/NotificationApi.Client/NotificationApiClient.cs, NotificationApi/NotificationApi/Controllers/HealthCheckController.cs, NotificationApi/NotificationApi/Extensions/ConfigureServicesExtensions.cs
VIH-6762
Renamed the route from HealthCheck to Health
```
[ ] Yes
[ ] No
```
=> VIH-6762 Renamed the route from HealthCheck to Health

NotificationApi/NotificationApi.AcceptanceTests/Hooks/ConfigHooks.cs, NotificationApi/NotificationApi.AcceptanceTests/NotificationApi.AcceptanceTests.csproj, NotificationApi/NotificationApi.AcceptanceTests/packages.lock.json, NotificationApi/NotificationApi.AcceptanceTests/parameters.runsettings, NotificationApi/NotificationApi.DAL/NotificationApi.DAL.csproj, NotificationApi/NotificationApi.DAL/appsettings.json, NotificationApi/NotificationApi.DAL/packages.lock.json, NotificationApi/NotificationApi.IntegrationTests/NotificationApi.IntegrationTests.csproj, NotificationApi/NotificationApi.IntegrationTests/packages.lock.json, NotificationApi/NotificationApi.UnitTests/packages.lock.json, NotificationApi/NotificationApi/packages.lock.json, NotificationApi/Testing.Common/Testing.Common.csproj
https://tools.hmcts.net/jira/browse/VIH-7058
- enabling test environment switching
```
[ ] Yes
[X] No
```
=> VIH-7058 adding test environment switching

NotificationApi/NotificationApi.AcceptanceTests/packages.lock.json, NotificationApi/NotificationApi.IntegrationTests/packages.lock.json, NotificationApi/NotificationApi.UnitTests/packages.lock.json, NotificationApi/NotificationApi/NotificationApi.csproj, NotificationApi/NotificationApi/Program.cs, NotificationApi/NotificationApi/packages.lock.json
VIH-7172 
Add new configuration provider for SDS
```
[ ] Yes
[x] No
```
=> VIH-7172 Add new configuration provider for SDS

azure-pipelines.release.yml
- Add test3 env
```
[ ] Yes
[X] No
```
=> VIH-5552 Add test3 env

NotificationApi/NotificationApi/Program.cs
VIH-7172
Also load config values from vh-infra-core folder
```
[ ] Yes
[ ] No
```
=> VIH-7172 Also load config values from vh-infra-core folder

NotificationApi/NotificationApi.Contract/NotificationType.cs, NotificationApi/NotificationApi.Domain/Enums/NotificationType.cs, NotificationApi/NotificationApi.UnitTests/Validation/AddNotificationRequestValidationTests.cs
VIH-6392
Add new notification types for:
* Hearing confirmation
* Hearing amendment
**NOTE: This does not include data migrations which have the template ids. This is to allow the front end work to continue.**
```
[ ] Yes
[x] No
```
=> VIH-6392 Add new notification types

NotificationApi/NotificationApi.AcceptanceTests/ApiTests/GetTemplateTests.feature, NotificationApi/NotificationApi.AcceptanceTests/Steps/GetTemplateSteps.cs
VIH-6392
Failing tests verify the which templates have the incorrect id against the db
```
[ ] Yes
[x] No
```
=> VIH-6392 Assert environment is setup during deployment

NotificationApi/NotificationApi.IntegrationTests/Database/Commands/CreateEmailNotificationCommandTests.cs, NotificationApi/NotificationApi.UnitTests/Validation/AddNotificationRequestValidationTests.cs, NotificationApi/Testing.Common/Extensions/AddNotificationRequestBuilder.cs
https://tools.hmcts.net/jira/browse/VIH-7304
- Update test email domain 
```
[ ] Yes
[x] No
```
=> VIH-7304 Updated test email domain names

NotificationApi/NotificationApi.AcceptanceTests/ApiTests/GetNotificationByParticipantAndHearingTests.feature, NotificationApi/NotificationApi.AcceptanceTests/ApiTests/GetPasswordNotificationTests.feature, NotificationApi/NotificationApi.AcceptanceTests/Steps/CommonSteps.cs, NotificationApi/NotificationApi.AcceptanceTests/Steps/GetNotificationByParticipantAndHearingSteps.cs, NotificationApi/NotificationApi.AcceptanceTests/Steps/GetPasswordNotificationSteps.cs, NotificationApi/NotificationApi.Client/NotificationApiClient.cs, NotificationApi/NotificationApi.Contract/Responses/NotificationResponse.cs, NotificationApi/NotificationApi.DAL/NotificationsApiDbContext.cs, NotificationApi/NotificationApi.DAL/Queries/GetNotificationByEmailQuery.cs, NotificationApi/NotificationApi.DAL/Queries/GetNotificationByParticipantAndHearingQuery.cs, NotificationApi/NotificationApi.IntegrationTests/ApiTests/GetNotificationByHearingAndParticipant.feature, NotificationApi/NotificationApi.IntegrationTests/ApiTests/GetPasswordNotificationByEmail.feature, NotificationApi/NotificationApi.IntegrationTests/Database/Queries/GetNotificationByEmailQueryTests.cs, NotificationApi/NotificationApi.IntegrationTests/Database/Queries/GetNotificationByParticipantAndHearingQueryTests.cs, NotificationApi/NotificationApi.IntegrationTests/Helper/TestDataManager.cs, NotificationApi/NotificationApi.IntegrationTests/Steps/GetNotificationByHearingAndParticipantSteps.cs, NotificationApi/NotificationApi.IntegrationTests/Steps/GetPasswordNotificationByEmailSteps.cs, NotificationApi/NotificationApi.UnitTests/Controller/Notification/GetNotificationByEmailTests.cs, NotificationApi/NotificationApi.UnitTests/Controller/Notification/GetNotificationByHearingAndParticipantTests.cs, NotificationApi/NotificationApi/Controllers/NotificationController.cs, NotificationApi/Testing.Common/Helper/ApiUriFactory.cs
https://tools.hmcts.net/jira/browse/VIH-7400
- Added functionality to get notifications by email, participant and hearing
- 
```
[ ] Yes
[x] No
```
=> VIH-7400 Added endpoints to get notifictions by email and hearing

NotificationApi/NotificationApi.AcceptanceTests/packages.lock.json, NotificationApi/NotificationApi.DAL/NotificationApi.DAL.csproj, NotificationApi/NotificationApi.DAL/packages.lock.json, NotificationApi/NotificationApi.IntegrationTests/packages.lock.json, NotificationApi/NotificationApi.UnitTests/packages.lock.json, NotificationApi/NotificationApi/NotificationApi.csproj, NotificationApi/NotificationApi/packages.lock.json
N/A
Get GovukNotify from NuGet
```
[ ] Yes
[x] No
```
=> VIH-1234 Get GovukNotify from NuGet

azure-pipelines.release.yml
tbc
Run ac tests during deployment except for prod
```
[ ] Yes
[x] No
```
=> VIH-7374 Run AC tests

azure-pipelines.release.yml
TBC
init env_runACTests variable
```
[ ] Yes
[x] No
```
=> VIH-1234 enable api test during deployment

NotificationApi/NotificationApi.DAL/Migrations/20210517144524_AddJudgeDemoOrTest.cs, NotificationApi/NotificationApi.DAL/Migrations/NotificationConfiguration.cs, NotificationApi/NotificationApi.DAL/Migrations/NotifySection.cs, NotificationApi/NotificationApi.DAL/Migrations/NotifyTemplateFactory.cs, NotificationApi/NotificationApi.DAL/Migrations/NotifyTemplates.cs
TBC
* Update config loading for templates to include environment variables
* Switch to nullable types to ensure the default GUID value is not used
```
[ ] Yes
[x] No
```
=> VIH-7335 fix config loading for migrations

azure-pipelines.release.yml, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-7660
```
[ ] Yes
[X] No
```
=> VIH-7660 - changed PAT

NotificationApi/NotificationApi.DAL/Migrations/20220405124535_AddTrackingDateTimeColumns.Designer.cs, NotificationApi/NotificationApi.DAL/Migrations/20220405124535_AddTrackingDateTimeColumns.cs, NotificationApi/NotificationApi.DAL/NotificationsApiDbContext.cs, NotificationApi/NotificationApi.Domain/ITrackable.cs, NotificationApi/NotificationApi.Domain/Notification.cs, NotificationApi/NotificationApi.Domain/Template.cs, NotificationApi/NotificationApi.IntegrationTests/Database/Commands/CreateEmailNotificationCommandTests.cs, NotificationApi/NotificationApi.IntegrationTests/Database/Commands/UpdateNotificationDeliveryStatusCommandTests.cs, NotificationApi/NotificationApi.IntegrationTests/Database/Commands/UpdateNotificationSentCommandHandlerTests.cs
**Before creating a pull request make sure that:**
- [x ] commit messages are meaningful and follow good commit message guidelines
- [ x] tests have been updated / new tests has been added (if needed)
```
[ ] Yes
[ x] No
```
=> VIH-8904 add tracking datetime columns

NotificationApi/NotificationApi.DAL/TemplateDataForEnvironments.cs, NotificationApi/NotificationApi/appsettings.json
…ings to secrets as this value is used by default if there is no variable is set
**Before creating a pull request make sure that:**
```
[ ] Yes
[x ] No
```
=> VIH-8955 DataSeedingChanges-TeamplateData

NotificationApi/NotificationApi.AcceptanceTests/ApiTests/GetTemplateTests.feature, NotificationApi/NotificationApi.AcceptanceTests/ApiTests/HearingConfirmation.feature, NotificationApi/NotificationApi.AcceptanceTests/Steps/HearingConfirmationSteps.cs, NotificationApi/NotificationApi.Contract/NotificationType.cs, NotificationApi/NotificationApi.DAL/Migrations/NotifyTemplates.cs, NotificationApi/NotificationApi.DAL/TemplateDataForEnvironments.cs, NotificationApi/NotificationApi.Domain/Enums/NotificationType.cs, NotificationApi/NotificationApi.IntegrationTests/ApiTests/GetTemplateByNotification.feature, azure-pipelines.release.yml, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-8853
```
[ ] Yes
[ x] No
```
=> VIH-8853 EJudge 48 hr reminder notification changes

NotificationApi/NotificationApi.AcceptanceTests/packages.lock.json, NotificationApi/NotificationApi.DAL/NotificationApi.DAL.csproj, NotificationApi/NotificationApi.DAL/packages.lock.json, NotificationApi/NotificationApi.IntegrationTests/packages.lock.json, NotificationApi/NotificationApi.UnitTests/packages.lock.json, NotificationApi/NotificationApi/NotificationApi.csproj, NotificationApi/NotificationApi/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-9073
```
[ ] Yes
[X ] No
```
=> VIH-9073 Upgraded govUkNotify nuget package to version 6

NotificationApi/NotificationApi.DAL/Commands/CreateEmailNotificationCommand.cs, NotificationApi/NotificationApi.DAL/Mappings/NotificationMap.cs, NotificationApi/NotificationApi.DAL/Migrations/20220614183446_AddParametersString.Designer.cs, NotificationApi/NotificationApi.DAL/Migrations/20220614183446_AddParametersString.cs, NotificationApi/NotificationApi.DAL/NotificationApi.DAL.csproj, NotificationApi/NotificationApi.DAL/Queries/GetEmailNotificationQuery.cs, NotificationApi/NotificationApi.DAL/Queries/GetTemplateByNotificationTypeQuery - Copy.cs, NotificationApi/NotificationApi.DAL/Queries/GetTemplateByNotificationTypeQuery.cs, NotificationApi/NotificationApi.DAL/appsettings.json, NotificationApi/NotificationApi.Domain/Notification.cs, NotificationApi/NotificationApi.IntegrationTests/Database/Commands/CreateEmailNotificationCommandTests.cs, NotificationApi/NotificationApi.IntegrationTests/Database/Queries/GetEmailNotificationQueryTests.cs, NotificationApi/NotificationApi.UnitTests/Services/NotifyServiceTests.cs, NotificationApi/NotificationApi/Controllers/NotificationController.cs, NotificationApi/NotificationApi/Properties/ServiceDependencies/vh-notification-api-demo - Web Deploy/profile.arm.json, NotificationApi/NotificationApi/Services/CreateNotificationService.cs
Storing the dictionary of parameter values passed in the request in the database. Validate whether the duplicate notifications are received.
```
[ ] Yes
[ x] No
```
=> VIH-8884 user creation and sending notifications

.github/workflows/close-pr.yml
VIH-9999
Add GitHub Action for PR Close.
```
[ ] Yes
[x ] No
```
=> VIH-9999  - Add Close PR Action

charts/vh-notification-api/Chart.yaml, charts/vh-notification-api/values.yaml
https://tools.hmcts.net/jira/browse/VIH-9019
Add a value from the vh-key-vault-vars ADO library 
```
[ ] Yes
[X ] No
```
=> VIH-9019 add a value to the chart.yaml

charts/vh-notification-api/Chart.yaml, charts/vh-notification-api/values.yaml
VIH-9329 
Update app settings
```
[ ] Yes
[ x  ] No
```
=> VIH-9329 - Update app settings

NotificationApi/NotificationApi.DAL/TemplateDataForEnvironments.cs
https://tools.hmcts.net/jira/browse/VIH-9342
Swapped Ids on template seed for dev
```
[ ] Yes
[X] No
```
=> VIH-9342 Template ids wrong way round for Multiday LIP and MultiDay Judge

azure-pipelines.sds.pr-release.yml, azure-pipelines.sds.release.yml
VIH-9241 - Amend EF Logic
VIH-9241 - Amend EF Logic
```
[ ] Yes
[x ] No
```
=> VIH-9241 - Amend EF Logic

charts/vh-notification-api/Chart.yaml, charts/vh-notification-api/values.yaml
re-add two secrets
```
[ ] Yes
[ x] No
```
=> VIH-9999 - Re-Add Secrets

NotificationApi/NotificationApi/Dockerfile
https://tools.hmcts.net/jira/browse/VIH-9477
Add curl to docket build
```
[ ] Yes
[ X] No
```
=> VIH-9477 Add curl to docker build

azure-pipelines.sds.release.yml
VIH-9191
Removing dependency
```
[ ] Yes
[X] No
```
=> VIH-9191 Removing dependency

azure-pipelines.sds.master-release.yml, azure-pipelines.sds.pr-close.yml, azure-pipelines.sds.pr-release.yml, azure-pipelines.sds.release.yml, variables/shared.yaml
VIH-9517 
Create master release
```
[ ] Yes
[X] No
```
=> VIH-9517 Create master release

azure-pipelines.sds.pr-release.yml
VIH-9532
Amend PR pipeline
```
[] Yes
[X] No
```
=> VIH-9532 Amend PR pipeline

azure-pipelines.sds.master-release.yml, azure-pipelines.sds.release.yml
https://tools.hmcts.net/jira/browse/VIH-9650?filter=-1
Remove Test Environment from SDS.
```
[ ] Yes
[X ] No
```
=> VIH-9650 removing test environment

azure-pipelines.sds.release.yml, variables/demo.yaml
https://tools.hmcts.net/jira/browse/VIH-9642
HMCTS have asked for the Demo environment for VH to be recreated.
This environment is to be used strictly for Demos and will have a copy of Production releases.
Create Demo Infra via Terraform (Core & Wowza)
Amend DNS
Configure AFD
Add Flux Configuration
Amend Release Pipelines to Run EF in Demo
```
[ ] Yes
[X ] No
```
=> VIH-9642 add demo to api

NotificationApi/NotificationApi.Client/NotificationApiClient.cs, NotificationApi/NotificationApi.DAL/Exceptions/DuplicateNotificationTemplateException.cs, NotificationApi/NotificationApi.IntegrationTests/Seeding/TemplateDataSeedingTests.cs, NotificationApi/NotificationApi/Controllers/NotificationController.cs, NotificationApi/NotificationApi/Startup.cs
VIH-9679
Update swagger doc for accurate deserialisation of response
```
[ ] Yes
[x] No
```
=> VIH-9679 Update swagger doc to match exception handler

NotificationApi/NotificationApi.DAL/TemplateDataSeeding.cs, NotificationApi/NotificationApi.IntegrationTests/Seeding/TemplateDataSeedingTests.cs
VIH-9678 
Slight variation in seeding method to check for db restore scenarios and duplicates rows
```
[ ] Yes
[x] No
```
=> VIH-9678 check the number of times a template appears

azure-pipelines.sds.master-release.yml, azure-pipelines.sds.pr-release.yml, azure-pipelines.sds.release.yml
VIH-9750 - Remove EF Conditional
```
[ ] Yes
[ x ] No
```
=> VIH-9750 - Remove EF Conditional

azure-pipelines.sds.master-release.yml
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> VIH-9999 - amend acceptance test checks

charts/vh-notification-api/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSPO-12091
Update java chart dependency to ensure compatibility with kubernetes 1.25
```
[ ] Yes
[x] No
```
=> VIH-0000 - Update chart deps

CODEOWNERS
https://tools.hmcts.net/jira/browse/VIH-9753
Add vh-qa team as codeowners
```
[ ] Yes
[x] No
```
=> VIH-9753 Update CODEOWNERS

azure-pipelines.sds.release.yml, variables/staging.yaml
https://tools.hmcts.net/jira/browse/VIH-9814
Add acceptance tests, split into staging and prod
```
[ ] Yes
[ X] No
```
=> VIH-9814 Amend Release Pipeline

azure-pipelines.sds.pr-release.yml, azure-pipelines.yml, docker-compose.tests.yml, scripts/tests/run-tests.sh, tests/Dockerfile, variables/shared.yaml, vh-api-sonar-settings.xml
VIH-9699
use new build test and anyalyse template
```
[ ] Yes
[x] No
```
=> VIH-9699 use new build test and analyse template

azure-pipelines.sds.release.yml
N/A
fix indentation error in sds release pipeline
```
[ ] Yes
[x] No
```
=> VIH-0000 fix indentation error in sds release pipeline

NotificationApi/NotificationApi.AcceptanceTests/packages.lock.json, NotificationApi/NotificationApi.Common/NotificationApi.Common.csproj, NotificationApi/NotificationApi.Common/Util/FeatureToggles.cs, NotificationApi/NotificationApi.Common/packages.lock.json, NotificationApi/NotificationApi.DAL/packages.lock.json, NotificationApi/NotificationApi.IntegrationTests/packages.lock.json, NotificationApi/NotificationApi.UnitTests/packages.lock.json, NotificationApi/NotificationApi/Startup.cs, NotificationApi/NotificationApi/packages.lock.json, charts/vh-notification-api/Chart.yaml, charts/vh-notification-api/values.yaml
VIH-9904
* add launch darkly feature toggle client
```
[ ] Yes
[x] No
```
=> VIH-9904 add launch darkly feature toggle client

NotificationApi/NotificationApi.AcceptanceTests/ApiTests/GetTemplateTests.cs, NotificationApi/NotificationApi.Contract/NotificationType.cs, NotificationApi/NotificationApi.DAL/TemplateDataForEnvironments.cs, NotificationApi/NotificationApi.Domain/Enums/NotificationType.cs, azure-pipelines.sds.pr-release.yml, azure-pipelines.yml
[VIH-9899](https://tools.hmcts.net/jira/browse/VIH-9899)
added new templates
=> VIH-9899 - added new templates and notification types

NotificationApi/NotificationApi/Middleware/Logging/RequestBodyLoggingMiddleware.cs, NotificationApi/NotificationApi/Startup.cs
VIH-10187
Add RequestBodyLogging Middleware
```
[ ] Yes
[x] No
```
=> VIH-10187 Add RequestBodyLogging Middleware

NotificationApi/NotificationApi/Health/HealthCheckExtensions.cs, charts/vh-notification-api/Chart.yaml, charts/vh-notification-api/values.yaml
VIH-10172
add old health check route for backwards compatibility
```
[ ] Yes
[x] No
```
=> VIH-10172 add old health check route for backwards compatibility

NotificationApi/NotificationApi.IntegrationTests/Api/ParticipantNotifications/SendParticipantSingleDayHearingConfirmationForNewUserEmailTests.cs, NotificationApi/NotificationApi.IntegrationTests/Api/ParticipantNotifications/SendParticipantWelcomeEmailTests.cs, NotificationApi/NotificationApi.IntegrationTests/appsettings.json, NotificationApi/NotificationApi/Controllers/ParticipantEmailNotificationsController.cs
https://tools.hmcts.net/jira/browse/VIH-10355
added notification for PM
=> VIH-10355 Creating a new Panel member unable to sent notifications

NotificationApi/Directory.Packages.props
=> VIH-10125 Disable CPM

NotificationApi/NotificationApi.Client/NotificationApi.Client.csproj, NotificationApi/NotificationApi.Contract/NotificationApi.Contract.csproj
https://tools.hmcts.net/jira/browse/VIH-10125
=> VIH-10125 Change client projects to target .NET standard

.github/CODEOWNERS, CODEOWNERS, azure-pipelines.sds.master-release.yml
See [VIH-10889](https://tools.hmcts.net/jira/browse/VIH-10889)
Adds Demo env to Entity Framework stage in master release pipeline
=> VIH-10889 Adds Demo env to Entity Framework stage in master release pipeline

NotificationApi/NotificationApi.AcceptanceTests/packages.lock.json, NotificationApi/NotificationApi.IntegrationTests/packages.lock.json, NotificationApi/NotificationApi.UnitTests/packages.lock.json, NotificationApi/NotificationApi/NotificationApi.csproj, NotificationApi/NotificationApi/Program.cs, NotificationApi/NotificationApi/packages.lock.json, azure-pipelines.sds.pr-release.yml
VIH-10993
* reload on config change for secret by file
* Remove deprecated VH.Core.Configuration
=> VIH-10993 Remove obsolete load keyvault file implementation

NotificationApi/NotificationApi.Contract/MessageType.cs, NotificationApi/NotificationApi.Contract/NotificationType.cs
https://tools.hmcts.net/jira/browse/VIH-11075
Removes obsolete attribute from enums that are still current and in use. Fixes warnings for the clients
=> VIH-11093 Remove obsolete attributes

azure-pipelines.sds.master-release.yml, variables/demo.yaml
See VIH-11181](https://tools.hmcts.net/jira/browse/VIH-11181)
enable demo image and helm buildpush
=> VIH-11181 enable demo image build push

.github/workflows/launch-darkly-find-code-refs-in-pr.yml, .github/workflows/launch-darkly-flag-sync.yml, .github/workflows/osv-scanner-pr.yml
VIH-11246
Update to the GitHub Actions:
* Switch the full LD code scan to run against master only and on a schedule
* Add the LD code scan on diff to run against PRs only
* Turn off fail on vuln for OSV scanner
=> VIH-11246 update GH actions

NotificationApi/NotificationApi.AcceptanceTests/packages.lock.json, NotificationApi/NotificationApi.Client/NotificationApi.Client.csproj, NotificationApi/NotificationApi.Client/NotificationApiClient.cs, NotificationApi/NotificationApi.Client/NotificationApiClientFactory.cs, NotificationApi/NotificationApi.Contract/NotificationApi.Contract.csproj, NotificationApi/NotificationApi.Contract/packages.lock.json, NotificationApi/NotificationApi.IntegrationTests/packages.lock.json, NotificationApi/NotificationApi.UnitTests/packages.lock.json, NotificationApi/NotificationApi/NotificationApi.csproj, NotificationApi/NotificationApi/nswag.json, NotificationApi/Testing.Common/Testing.Common.csproj
VIH-11248
Remove deprecated packages
Drop support for netstandard2.1
Minimum version is net6.0
Automation Tests
=> VIH-11248 remove deprecated packages

.github/renovate.json
VIH-11252
add renovate job for Helm Chart Release function
=> VIH-11252 Create renovate.json

charts/vh-notification-api/Chart.yaml, charts/vh-notification-api/values.dev.template.yaml, charts/vh-notification-api/values.yaml
Jira link
https://tools.hmcts.net/jira/browse/VIH-11295
Change description
Use latest Java base chart version so Azure Workload Identity is used
=> VIH-11295 update helm chart

azure-pipelines.sds.pr-release.yml
https://tools.hmcts.net/jira/browse/VIH-11302
=> VIH-11302 Remove references to obsolete variable groups

NotificationApi/NotificationApi.Common/Logging/CommandHandlerLoggingDecoratorLogger.cs, NotificationApi/NotificationApi.Common/Logging/CreateNotificationServiceLogger.cs, NotificationApi/NotificationApi.DAL/Commands/Core/CommandHandlerLoggingDecorator.cs, NotificationApi/NotificationApi/Controllers/ParticipantEmailNotificationsController.cs, NotificationApi/NotificationApi/Services/CreateNotificationService.cs, azure-pipelines.sds.pr-release.yml, azure-pipelines.sds.release.yml
VIH-9662
refactor: improve logging and error messages in notification services
The LoggerMessageAttribute generates strongly-typed logging methods at compile time, which helps in reducing the overhead associated with logging. This approach avoids the need to allocate memory for boxing and unboxing of parameters and reduces the cost of formatting the log message string at runtime.
=> VIH-9662 utilise LoggerMessage
